title: Alexander Samoshyn
description: Willkommen auf meiner persönlichen Webseite. Gerne gebe ich Ihnen einen kurzen Überblick von mir.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
